# Generated by Django 3.1.1 on 2020-10-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_newquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newquestion',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
