# Generated by Django 3.1.1 on 2020-10-14 21:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_post_draft'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('postadmin', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
