# Generated by Django 3.1.1 on 2020-10-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_auto_20201016_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
