# Generated by Django 3.1.1 on 2020-10-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_auto_20201016_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
