# Generated by Django 3.1.1 on 2020-10-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_auto_20201017_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='has_reply',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
