# Generated by Django 3.1.1 on 2020-10-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_auto_20201017_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Your email is protected and not seen by any third party.', max_length=254),
        ),
    ]
