# Generated by Django 3.1.1 on 2020-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0022_auto_20201029_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmarketing',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
