# Generated by Django 3.1.1 on 2020-10-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0023_emailmarketing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmarketing',
            name='receivers',
        ),
    ]
