# Generated by Django 3.1.1 on 2020-10-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20201011_0128'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='services',
            field=models.ManyToManyField(to='Home.Service'),
        ),
    ]
