# Generated by Django 3.1.1 on 2020-10-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='company',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
