# Generated by Django 3.1.1 on 2020-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201005_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
