# Generated by Django 3.1.1 on 2020-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201005_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
