# Generated by Django 3.1.1 on 2020-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20201005_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file_four',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_one',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_three',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_two',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
