# Generated by Django 3.1.1 on 2020-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20201005_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='meeting',
            field=models.CharField(blank=True, choices=[('G', 'Google/Internet search'), ('R', 'Referral'), ('O', 'Other')], max_length=1),
        ),
    ]
