# Generated by Django 3.1.1 on 2020-10-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
