# Generated by Django 3.1.1 on 2020-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=225),
        ),
    ]
