# Generated by Django 3.1.1 on 2020-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20201018_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('data', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, editable=False, max_length=225)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
