# Generated by Django 3.1.1 on 2020-10-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_ourindustry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurIndustry',
            new_name='Industry',
        ),
    ]
