# Generated by Django 3.1.1 on 2020-10-18 21:32

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20201018_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, upload_to=Home.models._image_upload),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to=Home.models._image_upload2),
        ),
    ]
