# Generated by Django 3.1.1 on 2020-10-18 22:13

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20201018_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(upload_to=Home.models._image_upload),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=Home.models._image_upload2),
        ),
    ]
